# Generated by Django 4.2 on 2023-04-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_musclegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='exercise',
            field=models.ManyToManyField(to='flex.exerciselist'),
        ),
    ]
