# Generated by Django 4.2 on 2023-04-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_remove_musclegroup_exercise_exerciselist_muscle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciselist',
            old_name='muscle',
            new_name='muscles',
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('exercises', models.ManyToManyField(to='flex.exerciselist')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='workouts',
            field=models.ManyToManyField(to='flex.workout'),
        ),
    ]
