# Generated by Django 4.2 on 2023-04-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_rename_muscle_exerciselist_muscles_workout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='workouts',
            field=models.ManyToManyField(null=True, to='flex.workout'),
        ),
    ]
