# Generated by Django 4.2 on 2023-04-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_workout_rename_muscle_exerciselist_muscles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercises',
            name='reps',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercises',
            name='sets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercises',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
