# Generated by Django 4.2 on 2023-04-19 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0007_alter_customuser_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='workouts',
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
